/*
	tabela de produtos

	LISTAR TODOS OS PRODUTOS 
	COLUNAS:
		ID_PRODUTO,DESCRICAO,PRECO_CUSTO,PRECO_VENDA
		CALCULAR :	PRECO_VENDA-PRECO_CUSTO
		FILTRAR : QUANDO PRECO_VENDA-PRECO_CUSTO >= 1.20
		ORDENAR POR QTDE_REAL
*/