SELECT ENDERECO + ' - ' +ISNULL(BAIRRO,'') + ' - ' + CIDADE + '/' +
ESTADO AS ENDERECO FROM TB_ENDERECO WHERE TIPO = 'PRINCIPAL';

SELECT ENDERECO , ' - ' ,ISNULL(BAIRRO,'') , ' - ' , CIDADE , '/' ,
ESTADO AS ENDERECO FROM TB_ENDERECO;

--CONCAT
SELECT
CONCAT(ENDERECO , ' - ' ,BAIRRO , ' - ' , CIDADE , '/' , ESTADO) AS ENDERECO

FROM TB_ENDERECO WHERE TIPO = 'PRINCIPAL';