CREATE VIEW TBV_FICHA_EMPREGADO
AS
SELECT E.*, C.CARGO, D.DEPARTAMENTO 
FROM     TB_EMPREGADO						AS E 
			LEFT JOIN	  TB_CARGO			AS C	ON E.ID_CARGO = C.ID_CARGO 
			LEFT JOIN    TB_DEPARTAMENTO	AS D	ON E.ID_DEPARTAMENTO = D.ID_DEPARTAMENTO
			LEFT JOIN	  TB_DEPENDENTE		AS DEP	ON DEP.ID_EMPREGADO = E.ID_EMPREGADO