--SELECT TOP 10 * FROM TB_EMPREGADO
set language 'brazilian'
SELECT  
NOME
--,FORMAT(DATA_ADMISSAO,'d','pt-br')
--,FORMAT(DATA_ADMISSAO,'dd/MM/yyyy')
--,CAST(DATA_ADMISSAO AS CHAR(12))
,FORMAT(DATA_ADMISSAO,'D')
,FORMAT(ISNULL(SALARIO,0),'C','PT-BR') AS SALÁRIO
,ISNULL(PREMIO_MENSAL,0) PREMIO_MENSAL
,ISNULL(SALARIO,0)+ISNULL(PREMIO_MENSAL,0) AS PROVENTO
FROM TB_EMPREGADO
ORDER BY SALARIO DESC --PROVENTO --SALARIO+PREMIO_MENSAL --DESC
