SELECT *, (QTD_REAL-QTD_MINIMA) AS SALDO
FROM TB_PRODUTO WHERE (QTD_REAL-QTD_MINIMA) <=0

SELECT ID_PEDIDO,STATUS,VLR_TOTAL,ID_EMPREGADO,ID_CLIENTE
FROM TB_PEDIDO WHERE VLR_TOTAL <500

SELECT *
FROM TB_ITENSPEDIDO
WHERE QUANTIDADE *PR_UNITARIO <> 0

SELECT * FROM TB_PEDIDO WHSELECT        
FROM            dbo.TB_CARGO INNER JOIN
                         dbo.TB_EMPREGADO ON dbo.TB_CARGO.ID_CARGO = dbo.TB_EMPREGADO.ID_CARGOERE STATUS = 'P'

